require('plugins_config.treesitter')
require "plugins_config.lualine"
require "plugins_config.indentline"
require "plugins_config.luatree"
require "plugins_config.ale_linters"
require "plugins_config.ale_fixers"
require "plugins_config.autosave"
require "plugins_config.spellcheck"
require "plugins_config.komentary"
require "plugins_config.test-vim"
