require('plugins_config.treesitter')
require "plugins_config.statusline"
require "plugins_config.indentline"
require "plugins_config.file_explorer"
require "plugins_config.ale_linters"
require "plugins_config.ale_fixers"
require "plugins_config.autosave"
require "plugins_config.spellcheck"
require "plugins_config.komentary"
require "plugins_config.test-vim"
require "plugins_config.tabline"
require "plugins_config.tree"
--require "plugins_config.hop"
require "plugins_config.dashboard"
require "plugins_config.autopairs"
require "plugins_config.trouble"
